name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Eliminar cache de Flutter
        run: rm -rf $HOME/flutter

      - name: Instalar Flutter 3.19.6
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.19.6 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          flutter doctor

      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK release
        run: flutter build apk --release

      - name: Renombrar APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-release.apk output/BiciXoel.apk

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: BiciXoel-APK
          path: output/BiciXoel.apk
